### ISSUE TITLE
Socket_Toolkit - Add functionality to know if another socket is listening

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Socket_Toolkit#16]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by rwemay** [comment]
@IsakNaslundBh is this issue still live/an issue?

**Comment by adecler** [comment]
Closing as functionality of the socket is sufficient for current usage
