### ISSUE TITLE
Socket_Engine: add a way to perform a GET request

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Socket_Toolkit#41]

**Comment by adecler** [comment]
What do you mean? Sockets are for volatile data.

**Comment by epignatelli** [comment]
I need a place to create a method that make a GET request to a REST API.
I proposed socket because that's the only communication toolkit we have and I noticed there is not a Socket_Engine.

If this is not the best place. I am fine to push it somewhere else!

**Comment by epignatelli** [comment]
After out last chat, closing this in favour of https://github.com/BHoM/HTTP_Toolkit/issues/1
