### ISSUE TITLE
Socket_Toolkit: Live sync issue from Grasshopper to Dyanmo

### ISSUE THREAD

**Issue by nirbhay93** [BHoM/Socket_Toolkit#42]
Geometry in Dynamo doesn't get automatically updated when pushing from Grasshopper using socket adapter. User has to manually refresh the boolean state in Dynamo. However, live sync using socket adapter works perfectly fine when pushing from Dynamo to Grasshopper.

Yammer post for reference: https://www.yammer.com/burohappold.com/threads/1234323753

**Comment by FraserGreenroyd** [comment]
Issue has not been brought up in recent years so is assumed to have disappeared, or different workflows implemented.
